version: "3.8"

services:
  mlflow:
    image: python:3.11-slim
    container_name: mlflow_server
    command: >
      bash -c "pip install mlflow &&
               mlflow server
               --host 0.0.0.0
               --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.api
    container_name: compagnon_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow